Snana naturals
asharanjith/Capstone-Project-1 pull request #1
Opened 2022-10-20 08:44 UTC by asharanjith

2022-10-20 13:23 UTC, jerryowusu requested changes
Hi @asharanjith :wave: 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

![no-we-were-so-close-pauline-turner-brooks](https://user-images.githubusercontent.com/65233860/196960516-72b6809c-8832-4d1e-852e-3c894cea55e4.gif)

## Suggested changes 

- [ ] The project documentation video looks nice and proffessional. :1st_place_medal:  Unfortunately, it is missing one key requirement for the video as shown below in the project documentation image (check the 3rd bullet point). Kindly make sure that you highlight some interesting piece of code or something you built that you are very proud of: :smiley: 

![Screenshot from 2022-10-20 00-23-06](https://user-images.githubusercontent.com/65233860/196829920-8dc60a90-86c3-47b1-a18d-bec80de72b43.png)


_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-10-20 13:23 UTC, jerryowusu commented on README.md
> + This is a demo of the Capstone[Demo](https://www.loom.com/share/97c0b1f80a9f44b4b501bdbc72fbc848)
The project documentation video looks nice and proffessional. :1st_place_medal:  Unfortunately, it is missing one key requirement for the video as shown below in the project documentation image (check the 3rd bullet point). Kindly make sure that you highlight some interesting piece of code or something you built that you are very proud of: :smiley: 



![Screenshot from 2022-10-20 00-23-06](https://user-images.githubusercontent.com/65233860/196829920-8dc60a90-86c3-47b1-a18d-bec80de72b43.png)

2022-10-20 13:23 UTC, jerryowusu commented on css/main.scss
> +        list-style: none;
Kindly align the page links to the right and not center in conformity with the design. :pray:

2022-10-20 13:23 UTC, jerryowusu commented on css/main.scss
> +      }
[OPTIONAL] Just as was done for the mobile menu in the personal portfolio website, it would be nice and more professional if your mobile menu covers the whole of the page instead of the design below.
 
![Screenshot from 2022-10-20 12-37-26](https://user-images.githubusercontent.com/65233860/196950784-1d26734b-2195-4e36-b23b-07debe71c66b.png)

2022-10-20 13:23 UTC, jerryowusu commented on index.html
> +            </footer>
- [ ] Kindly make sure that the logo is aligned to the left whilst the text is aligned right as shown in the actual design below.
- [ ]  The footer of about page (desktop version) should have a dark background instead of the white you applied.


Your design             |  The actual design
:-------------------------:|:-------------------------:
![Screenshot from 2022-10-20 12-47-38](https://user-images.githubusercontent.com/65233860/196952726-4eb96f0a-2416-4e37-92ee-d36a8ef17045.png)  |  ![Screenshot from 2022-10-20 12-47-27](https://user-images.githubusercontent.com/65233860/196952759-f08749f8-d888-4d52-ba64-1d6772c97942.png)

2022-10-20 13:23 UTC, jerryowusu commented on index.html
> +                        </div>
The pages should use the exact same colors, for text, backgrounds, borders, etc, from the original design. All page elements should have similar spacing, borders, shadows, and paddings than the orignal design. I can see some differences between your design and the actual design, the colors, spacing padding etc as shown below. Kindly check and rectify this anomaly. Below are just a few examples


Your design             |  The actual design
:-------------------------:|:-------------------------:
![Screenshot from 2022-10-20 12-54-07](https://user-images.githubusercontent.com/65233860/196954907-fbb0aa89-6a1a-4b26-bea4-4bf8d0e4e72f.png)  |  ![Screenshot from 2022-10-20 12-53-57](https://user-images.githubusercontent.com/65233860/196955077-819a6415-bb06-4663-8536-9c2fa229e279.png)

Your design             |  The actual design
:-------------------------:|:-------------------------:
![Screenshot from 2022-10-20 13-03-14](https://user-images.githubusercontent.com/65233860/196956325-3c5ad9cd-d756-4d68-b942-92842a25e344.png)  |  ![Screenshot from 2022-10-20 13-03-27](https://user-images.githubusercontent.com/65233860/196956359-f59012f0-f634-4ce6-bbfe-2fc8869286d3.png)



Your design             |  The actual design
:-------------------------:|:-------------------------:
![Screenshot from 2022-10-20 13-14-21](https://user-images.githubusercontent.com/65233860/196958535-2ae1200b-e0bf-4ab1-8b61-8d995d2d1e8a.png)  |  ![Screenshot from 2022-10-20 13-14-01](https://user-images.githubusercontent.com/65233860/196958564-88cc7796-fa4d-406c-bfef-2b8b89be9caa.png)

2022-10-20 13:23 UTC, jerryowusu commented on index.html
> +            </section>
The speaker section of the desktop version should be organized in two columns of three articles each. Currently your desktop version below screen width 1245px displays only single columns. Kindly check and correct this. :pray: 

Your design             |  The actual design
:-------------------------:|:-------------------------:
![Screenshot from 2022-10-20 13-06-02](https://user-images.githubusercontent.com/65233860/196957504-ddd54e60-c52d-4de7-bb04-0dde7b0af128.png)  |  ![Screenshot from 2022-10-20 13-06-23](https://user-images.githubusercontent.com/65233860/196957526-bd681c92-9d62-4947-a7dd-fefd6907f8b2.png)


Your design             |  The actual design
:-------------------------:|:-------------------------:
![Screenshot from 2022-10-20 13-10-50](https://user-images.githubusercontent.com/65233860/196957746-35d09979-d43e-4eb8-a481-43f0d1d520ce.png)  |  ![Screenshot from 2022-10-20 13-06-23](https://user-images.githubusercontent.com/65233860/196957783-5b3d9ef8-e3b3-4717-b9f7-d5f8cf7c6fc0.png)

2022-10-20 13:23 UTC, jerryowusu commented on index.html
> +
Each of the program items are articles hence it will be better to put them in article tags for SEO optimization and accessibility factors.

2022-10-20 16:08 UTC, mckent05 requested changes
Hi @asharanjith,

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- All linter checks are passing ✔️ ✔️ 
- GitHub flow is correctly followed 👏 
- Descriptive PR summary and PR title 👍 👍 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your code.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-20 16:08 UTC, mckent05 commented on index.html
> +                </div>
**OPTIONAL**- For  HTML semantic and improved accessibility reasons, it is not advisable that you have 3 `nav` tags in your HTML file, I'd suggest you have just one `nav` tag and wrap all needed elements in it. Please fix this 🙏

**OPTIONAL** - Your navbar does not exactly look like the one in the design template, there are differences in the alignment of the social links (it is centered vertically in the middle, in the template, while it is centered towards the bottom in your design). Also, the links are not exactly the same as what is in the template (text color,  font weight). Please I'd advise you to fix this. Remember it is important that you try to replicate the Figma design as closely as possible to give confidence to recruiters in your ability to produce exact business requirements 🙏

Your project:
<img width="950" alt="navbar capstone" src="https://user-images.githubusercontent.com/73607512/196994123-e4114755-5027-47cb-9636-b912b2d2fa5a.PNG">

Design template:
<img width="628" alt="navbar behance" src="https://user-images.githubusercontent.com/73607512/196994233-096ac0ca-cd00-4a97-877c-7235884f665f.PNG">

2022-10-20 16:08 UTC, mckent05 commented on index.html
> +                            <p>This is your chance to be part of the conversation.</p>
- Just as the previous reviewer stated, this section of your page doesn't match the design template,  while it is good to personalize some content in this project, you are required to stick to the general layout given in the design (background colors, text color, font-weight, font size e.t.c). Please make sure that you replicate this section as it is in the design template 😄 😄. Remember it is important that you try to replicate the Figma design as closely as possible to give confidence to recruiters in your ability to produce exact business requirements 🙏

Your project:
<img width="960" alt="program card today 2" src="https://user-images.githubusercontent.com/73607512/196997514-5bd90ccc-40cb-437e-8e08-dc46b04dc9af.PNG">

Design Template:
<img width="625" alt="program beance" src="https://user-images.githubusercontent.com/73607512/196997586-66066c41-1157-4afb-b1c8-88f79f40cc15.PNG">

2022-10-20 16:08 UTC, mckent05 commented on index.html
> +            </section>
**OPTIONAL** - For improved SEO optimization I'd suggest you wrapped each of the sponsors in a `li` tag and then wrap all the `li` tags in a `ul` tag 👍 👍 

- Just as the previous reviewer stated and as I said above, please try as much as possible to stick to the general design layout, (background color, font color, font weight, font size e.t.c). This section of your page doesn't exactly match the given design template. Please try to fix it 🙏 🙏 

Your project(please pay attention to the header text color, and the color of the section background):
<img width="960" alt="partners" src="https://user-images.githubusercontent.com/73607512/196999921-01020c4a-01d3-41be-99aa-7721e2f17539.PNG">

Design template:
<img width="625" alt="partners behance" src="https://user-images.githubusercontent.com/73607512/197000063-6e9f0e75-7d90-45b9-bef6-83e667f5ba23.PNG">

2022-10-20 16:08 UTC, mckent05 commented on index.html
> +            </section>
**OPTIONAL** - There are some little variations in the text color for your page header. Please remember to stick to the general layout of the design template 👍 .

Your project(Please pay attention to the text color): 
<img width="627" alt="header text student" src="https://user-images.githubusercontent.com/73607512/197000782-c279d8c7-7f88-4ad6-8993-9f5225d0b879.PNG">

Design template:
<img width="624" alt="header text behnace" src="https://user-images.githubusercontent.com/73607512/197000858-dbf40d39-97f4-4453-9d22-7ad7bc8b48f6.PNG">

2022-10-21 04:34 UTC, Santiago220991 approved these changes
Hi @asharanjith, 
I'm Santiago your reviewer for this PR. :wave: :wave: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/tIeCLkB8geYtW/giphy.gif"/>

## Highlights
:heavy_check_mark: Applied changes suggested by the last reviewer.
:heavy_check_mark: Followed GitHub flow.
:heavy_check_mark: No linter errors

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-21 04:34 UTC, Santiago220991 commented on speakercard.js
> +      button.innerHTML = 'More<i class="fas fa-chevron-down"></i>';
[OPTIONAL] I think you did a great job with the MORE button, however, kindly make sure that the button is still working after clicking on it twice. The button stops working when trying to click on it a third time. :eyes: :eyes: 
![image](https://user-images.githubusercontent.com/98363075/197112696-6d26347a-3b33-4ac2-be89-bc58b93feaf9.png)

2022-10-21 04:43 UTC, merged